id: cb4fa41f00e24e9283633a13be493f5f
initial_creation_type: ocr
source_metadata:
  volumes:
    e9380eaa60754575a7dd99b6e43cfbf1:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
