id: DB8FC8F14
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:37:38+00:00'
last_modified: '2022-05-27T15:31:28.576440+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f6d0:
      image_group_id: I1PD95909
      title: སྐྱབས་སུ་འགྲོ་བ་བསྟན་པ།
      total_pages: 1902
      order: 64
      base_file: f6d0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
